print(" *** 30% of Number ***")
x=input("Enter a number : ")
print()
print("The number =",x,type(x))
x=int(x)
print("The number =",x,type(x))
x=float(x)
print("The number =",x,type(x))
print("30 %% = %.5f"%(x*0.3))
print("30 %% = %.3f"%(x*0.3))
print("30 %% = %.1f"%(x*0.3))
